### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by kittinunf** [brianegan/bansa#19]
Thank you so much for your work on this. It is really nice library. I am a big fan of Redux.

1. Can you share why you decide to move implementation away from Kotlin -> Java?
2. Do you have any support for [StoreEnhancer](https://github.com/reactjs/redux/blob/64a8c66b454163660f9d49bcce92a3230cdbcb2a/docs/Glossary.md#store-enhancer) ?

**Comment by brianegan** [comment]
Sure thing... 

  1. A couple reasons. I want this pattern to be more easily accessible to Java Devs. After speaking with a few peeps, it seemed Kotlin was a barrier to entry for some. I didn't want that. Secondly, Kotlin requires about 6000 methods between the std lib + runtime. This little library only uses 41 methods, so adding such a huge method count dependency seemed like overkill. Finally, the interface only slightly changed when I moved away from Kotlin. Therefore, the drawbacks were minor, but the wins were big.

  2. I don't have explicit support for a `StoreEnhancer` type as it seemed like quite a functional concept and I was trying to stick more closely to Java Design patterns which is decidedly less functional. Also, I didn't see a huge design advantage to using Store Enhancers rather than wrapping / mutating instances as that's all that's happening under the hood in `applyMiddleware` from the original redux (see https://github.com/reactjs/redux/blob/64a8c66b454163660f9d49bcce92a3230cdbcb2a/src/applyMiddleware.js#L21). So you could still create several "Store Enancers" by composing instances like so: `new WrappedStore(new BaseStore(...)) `. This is essentially how the Dev Tools in this repo works!

**Comment by kittinunf** [comment]
Thanks for your kind answers.

1. Ah, I see. For me, I already used Kotlin so it doesn't effect me. But you answer makes sense.

2. I would love to have something that can sync my Redux store into a persistent storage. In my opinion, the cleanest way to do this is to have a Store Enhancer wrapped over Store and perform serialize/deserialize state into storage for us. I do respect you answer that you want `bansa` to follow closely to Java design paradigm.

**Comment by brianegan** [comment]
Ah, I certainly understand the need for the second! However, rather than a store enhancer, you should be able to achieve that goal in two ways:

  1.  Create a "persistence controller" that listens to state changes and writes to the database every time a state change occurs. 
  2. Create a middleware that operates on specific actions and writes to the dB / network when those actions are dispatched. 

Do one of those two options work? If not, let me know and I'll think more about the store enhancer concept!
